name = "json"
description = "A SPARK JSON parser proved to Silver (fork of onox/json-ada)"
version = "7.1.0"
website = "https://github.com/manthonyaiello/json-spark"
licenses = "Apache-2.0"
tags = ["json", "spark"]

project-files = ["json.gpr"]

authors = ["onox"]
maintainers = ["M. Anthony Aiello <m.anthony.aiello@gmail.com>"]
maintainers-logins = ["manthonyaiello"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM120-Is"]
